TRANSLATIONS = {
    "en": {
        # directions & distances
        "Left":             "Left",
        "Right":            "Right",
        "Front":            "Front",
        "very close, stop": "very close, stop",
        "close":            "close",
        "nearby":           "nearby",
        "far":              "far",
        "Careful":          "Careful",
        "and":              "and",

        # YOLO classes
        "person":           "person",
        "bicycle":          "bicycle",
        "car":              "car",
        "motorcycle":       "motorcycle",
        "airplane":         "airplane",
        "bus":              "bus",
        "train":            "train",
        "truck":            "truck",
        "boat":             "boat",
        "traffic light":    "traffic light",
        "fire hydrant":     "fire hydrant",
        "stop sign":        "stop sign",
        "parking meter":    "parking meter",
        "bench":            "bench",
        "bird":             "bird",
        "cat":              "cat",
        "dog":              "dog",
        "horse":            "horse",
        "sheep":            "sheep",
        "cow":              "cow",
        "elephant":         "elephant",
        "bear":             "bear",
        "zebra":            "zebra",
        "giraffe":          "giraffe",
        "backpack":         "backpack",
        "umbrella":         "umbrella",
        "handbag":          "handbag",
        "tie":              "tie",
        "suitcase":         "suitcase",
        "frisbee":          "frisbee",
        "skis":             "skis",
        "snowboard":        "snowboard",
        "sports ball":      "sports ball",
        "kite":             "kite",
        "baseball bat":     "baseball bat",
        "baseball glove":   "baseball glove",
        "skateboard":       "skateboard",
        "surfboard":        "surfboard",
        "tennis racket":    "tennis racket",
        "bottle":           "bottle",
        "wine glass":       "wine glass",
        "cup":              "cup",
        "fork":             "fork",
        "knife":            "knife",
        "spoon":            "spoon",
        "bowl":             "bowl",
        "banana":           "banana",
        "apple":            "apple",
        "sandwich":         "sandwich",
        "orange":           "orange",
        "broccoli":         "broccoli",
        "carrot":           "carrot",
        "hot dog":          "hot dog",
        "pizza":            "pizza",
        "donut":            "donut",
        "cake":             "cake",
        "chair":            "chair",
        "couch":            "couch",
        "potted plant":     "potted plant",
        "bed":              "bed",
        "dining table":     "dining table",
        "toilet":           "toilet",
        "tv":               "tv",
        "laptop":           "laptop",
        "mouse":            "mouse",
        "remote":           "remote",
        "keyboard":         "keyboard",
        "cell phone":       "cell phone",
        "microwave":        "microwave",
        "oven":             "oven",
        "toaster":          "toaster",
        "sink":             "sink",
        "refrigerator":     "refrigerator",
        "book":             "book",
        "clock":            "clock",
        "vase":             "vase",
        "scissors":         "scissors",
        "teddy bear":       "teddy bear",
        "hair drier":       "hair drier",
        "toothbrush":       "toothbrush",
    },
    "ar": {
        # اتجاهات ومسافات
        "Left":             "على اليسار",
        "Right":            "على اليمين",
        "Front":            "أمامك",
        "very close, stop": "قريب جداً توقف",
        "close":            "قريب",
        "nearby":           "متوسط",
        "far":              "بعيد",
        "Careful":          "انتبه",
        "and":              "و",

        # أسماء الأشياء
        "person":           "شخص",
        "bicycle":          "دراجة",
        "car":              "سيارة",
        "motorcycle":       "دراجة نارية",
        "airplane":         "طيارة",
        "bus":              "باص",
        "train":            "قطار",
        "truck":            "شاحنة",
        "boat":             "قارب",
        "traffic light":    "إشارة مرور",
        "fire hydrant":     "حنفية حريق",
        "stop sign":        "لافتة قف",
        "parking meter":    "عداد موقف",
        "bench":            "مقعد",
        "bird":             "طائر",
        "cat":              "قطة",
        "dog":              "كلب",
        "horse":            "حصان",
        "sheep":            "خروف",
        "cow":              "بقرة",
        "elephant":         "فيل",
        "bear":             "دب",
        "zebra":            "حمار وحشي",
        "giraffe":          "زرافة",
        "backpack":         "حقيبة ظهر",
        "umbrella":         "مظلة",
        "handbag":          "حقيبة يد",
        "tie":              "ربطة عنق",
        "suitcase":         "حقيبة سفر",
        "frisbee":          "فريسبي",
        "skis":             "زلاجات",
        "snowboard":        "لوح ثلج",
        "sports ball":      "كرة",
        "kite":             "طائرة ورقية",
        "baseball bat":     "مضرب بيسبول",
        "baseball glove":   "قفاز بيسبول",
        "skateboard":       "لوح تزلج",
        "surfboard":        "لوح تزلج مائي",
        "tennis racket":    "مضرب تنس",
        "bottle":           "زجاجة",
        "wine glass":       "كأس",
        "cup":              "كوب",
        "fork":             "شوكة",
        "knife":            "سكين",
        "spoon":            "ملعقة",
        "bowl":             "وعاء",
        "banana":           "موزة",
        "apple":            "تفاحة",
        "sandwich":         "ساندويتش",
        "orange":           "برتقالة",
        "broccoli":         "بروكلي",
        "carrot":           "جزرة",
        "hot dog":          "هوت دوج",
        "pizza":            "بيتزا",
        "donut":            "دونات",
        "cake":             "كيك",
        "chair":            "كرسي",
        "couch":            "أريكة",
        "potted plant":     "نبتة",
        "bed":              "سرير",
        "dining table":     "طاولة",
        "toilet":           "مرحاض",
        "tv":               "تلفزيون",
        "laptop":           "لابتوب",
        "mouse":            "ماوس",
        "remote":           "ريموت",
        "keyboard":         "كيبورد",
        "cell phone":       "موبايل",
        "microwave":        "ميكروويف",
        "oven":             "فرن",
        "toaster":          "توستر",
        "sink":             "حوض",
        "refrigerator":     "ثلاجة",
        "book":             "كتاب",
        "clock":            "ساعة",
        "vase":             "مزهرية",
        "scissors":         "مقص",
        "teddy bear":       "دبدوب",
        "hair drier":       "مجفف شعر",
        "toothbrush":       "فرشاة أسنان",
    }
}


def t(key, lang):
    """ترجم أي كلمة للغة المختارة — لو مش موجودة رجّع الكلمة الأصلية"""
    return TRANSLATIONS.get(lang, TRANSLATIONS["en"]).get(key, key)